let questions = [
    { numb: 1, question: "I like to work on cars", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 2, question: "I like to do puzzles", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 3, question: "I am good at working independently", answer: "True", Option: ["True", "Flase"], id: "A" },
    { numb: 4, question: "I like to work in teams", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 5, question: "I am an ambitious person, I set goals for myself", answer: "True", Option: ["True", "Flase"], id: "E" },
    { numb: 6, question: "I like to organize things,(files, desks/offices)", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 7, question: "I like to build things", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 8, question: "I like to read about art and music", answer: "True", Option: ["True", "Flase"], id: "A" },
    { numb: 9, question: "I like to have clear instructions to follow", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 10, question: "I like to try to influence or persuade people", answer: "True", Option: ["True", "Flase"], id: "E" },
    { numb: 11, question: "I like to do experiments", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 12, question: "I like to teach or train people", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 13, question: "I like trying to help people solve their problems", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 14, question: "I like to take care of animals", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 15, question: "I wouldn’t mind working 8 hours per day in an office", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 16, question: "I like selling things", answer: "True", Option: ["True", "Flase"], id: "E" },
    { numb: 17, question: "I enjoy creative writing", answer: "True", Option: ["True", "Flase"], id: "A" },
    { numb: 18, question: ". I enjoy science", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 19, question: "I am quick to take on new responsibilities", answer: "True", Option: ["True", "Flase"], id: "E" },
    { numb: 20, question: "I am interested in healing people", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 21, question: ". I enjoy trying to figure out how things work", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 22, question: "I like putting things together or assembling things", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 23, question: "I am a creative person", answer: "True", Option: ["True", "Flase"], id: "A" },
    { numb: 24, question: "I pay attention to details", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 25, question: "I like to do filing or typing", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 26, question: "I like to analyze things (problems/situations)", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 27, question: "I like to play instruments or sing", answer: "True", Option: ["True", "Flase"], id: "A" },
    { numb: 28, question: "I enjoy learning about other cultures", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 29, question: "I would like to start my own business", answer: "True", Option: ["True", "Flase"], id: "E" },
    { numb: 30, question: "I like to cook", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 31, question: "I like acting in plays", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 32, question: "I am a practical person", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 33, question: "I like working with numbers or charts", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 34, question: ". I like to get into discussions about issues", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 35, question: "I am good at keeping records of my work", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 36, question: "I like to lead", answer: "True", Option: ["True", "Flase"], id: "E" },
    { numb: 37, question: "I like working outdoors", answer: "True", Option: ["True", "Flase"], id: "R" },
    { numb: 38, question: "I would like to work in an office", answer: "True", Option: ["True", "Flase"], id: "C" },
    { numb: 39, question: "I’m good at math", answer: "True", Option: ["True", "Flase"], id: "I" },
    { numb: 40, question: ". I like helping people", answer: "True", Option: ["True", "Flase"], id: "S" },
    { numb: 41, question: "I like to draw", answer: "True", Option: ["True", "Flase"], id: "A" },
    { numb: 42, question: "I like to give speeches", answer: "True", Option: ["True", "Flase"], id: "E" },

]